- name: Play Variables # play level variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
         msg: URL == {{ URL }}

- name: Play Variables from file
  ## varaiables from files
  hosts: localhost
  ## varaiables from files works only on play level
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from files
      ansible.builtin.debug:
        msg: URL == {{ URL }}

## task level variables
- name: Task level  Variables
  hosts: localhost
  tasks:
    - name: print play variable from files
      vars: ## thses vars are only  for this task , next task cannot acess this
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL == {{ URL }}

## Inventory level variables
- name: vars from inventory
  hosts: all
  tasks:
    - name: print play variable from INVENTORY
      ansible.builtin.debug:
        msg: "URL == {{ URL }}, hostname of servers = {{ ansible_hostname }}"

- name: Registered variable
  hosts: localhost
  tasks:
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: out

    - name: print out
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Declare a variable
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"