- name : Play Variables
  hosts : localhost
  vars :
    URL: play.example.com
    website : www.sirisha.com
  tasks :
    - name : print play variable
      ansible.builtin.debug:
         msg: [ URL == {{ URL }} , website == {{ website }}]